# Generated by Django 5.0.7 on 2024-08-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='subjects',
            field=models.ManyToManyField(null=True, to='subject.subject'),
        ),
    ]
