# Generated by Django 5.0.7 on 2024-08-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.major')),
            ],
        ),
    ]
