# Generated by Django 5.0.7 on 2024-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='detail',
            field=models.JSONField(default={}),
        ),
    ]
