# Generated by Django 5.0.7 on 2024-08-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='detail',
            field=models.JSONField(default=None, null=True),
        ),
    ]
