# Generated by Django 5.0.7 on 2024-08-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentterm',
            old_name='gpa',
            new_name='gps',
        ),
    ]
